
site_name: bibliofabric Docs
site_url: https://utsmok.github.io/bibliofabric/
repo_url: https://github.com/utsmok/bibliofabric/
site_author: S. Mok

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
nav:
  - Home: index.md
  - API Reference:
    - Client: client.md
    - Configuration: config.md
    - Resources: resources.md
    - Models: models.md
    - Authentication: auth.md
    - Exceptions: exceptions.md
watch:
  - src/bibliofabric
